"""phase2 forecast columns

Revision ID: 1c3d9dad1ad0
Revises: 33a3ea42f01c
Create Date: 2026-08-14 21:15:51.187584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3d9dad1ad0'
down_revision: Union[str, None] = '33a3ea42f01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('baseline_pct_change', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('driver_pct_change', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('ml_pct_change', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('disagreement_level', sa.String(length=16), nullable=True))
    op.add_column('forecasts', sa.Column('data_mode', sa.String(length=16), nullable=True))
    op.add_column('forecasts', sa.Column('regime_change_detected', sa.Boolean(), nullable=False))
    op.add_column('forecasts', sa.Column('mae', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('rmse', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('mape', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('directional_accuracy', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('interval_coverage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'interval_coverage')
    op.drop_column('forecasts', 'directional_accuracy')
    op.drop_column('forecasts', 'mape')
    op.drop_column('forecasts', 'rmse')
    op.drop_column('forecasts', 'mae')
    op.drop_column('forecasts', 'regime_change_detected')
    op.drop_column('forecasts', 'data_mode')
    op.drop_column('forecasts', 'disagreement_level')
    op.drop_column('forecasts', 'ml_pct_change')
    op.drop_column('forecasts', 'driver_pct_change')
    op.drop_column('forecasts', 'baseline_pct_change')
    # ### end Alembic commands ###
