"""initial schema

Revision ID: 33a3ea42f01c
Revises: 
Create Date: 2026-08-14 15:01:37.371512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a3ea42f01c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('default_lag_days', sa.Integer(), nullable=False),
    sa.Column('directionality', sa.String(length=16), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('affected_driver', sa.String(length=255), nullable=True),
    sa.Column('affected_material', sa.String(length=255), nullable=True),
    sa.Column('impact_direction', sa.String(length=16), nullable=False),
    sa.Column('impact_magnitude', sa.String(length=16), nullable=False),
    sa.Column('impact_horizon', sa.String(length=16), nullable=False),
    sa.Column('event_confidence', sa.Float(), nullable=True),
    sa.Column('processed_by_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('current_price_date', sa.Date(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('single_source_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_material_code'), 'materials', ['material_code'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supplier_code', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('qualification_status', sa.String(length=32), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('single_source', sa.Boolean(), nullable=False),
    sa.Column('share_of_supply', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_table('driver_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('point_forecast', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('component_code', sa.String(length=32), nullable=True),
    sa.Column('percentage_of_cost', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('contract_type', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('data_quality', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('previous_price', sa.Float(), nullable=True),
    sa.Column('claimed_change_pct', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('relationship_strength', sa.Float(), nullable=False),
    sa.Column('elasticity', sa.Float(), nullable=True),
    sa.Column('lag_period', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['material_components.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confidence_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('data_score', sa.Float(), nullable=False),
    sa.Column('driver_score', sa.Float(), nullable=False),
    sa.Column('model_score', sa.Float(), nullable=False),
    sa.Column('market_score', sa.Float(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_id')
    )
    op.create_table('forecast_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('contribution_value', sa.Float(), nullable=False),
    sa.Column('contribution_pct', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('recommended_duration', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('recommendations')
    op.drop_table('forecast_contributions')
    op.drop_table('confidence_components')
    op.drop_table('component_drivers')
    op.drop_table('supplier_quotes')
    op.drop_table('price_observations')
    op.drop_table('material_components')
    op.drop_table('forecasts')
    op.drop_table('driver_observations')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_materials_material_code'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('market_events')
    op.drop_table('drivers')
    # ### end Alembic commands ###
